### ISSUE TITLE
Tests are not working

### ISSUE THREAD

**Issue by chokdee** [christophd/citrus-samples-xml#2]
1) checked out a fresh copy
2) running the mvn commands
3) tests failed
[ERROR]   RouteMessagesHttpIT>AbstractTestNGCitrusTest.run:70->AbstractTestNGCitrusTest.run:108->AbstractTestNGCitrusTest.invokeTestMethod:124 » TestCaseFailed
[ERROR]   RouteMessagesHttpIT>AbstractTestNGCitrusTest.run:70->AbstractTestNGCitrusTest.run:108->AbstractTestNGCitrusTest.invokeTestMethod:124 » TestCaseFailed
[ERROR]   RouteMessagesJmsIT>AbstractTestNGCitrusTest.run:70->AbstractTestNGCitrusTest.run:108->AbstractTestNGCitrusTest.invokeTestMethod:124 » TestCaseFailed
[ERROR]   RouteMessagesJmsIT>AbstractTestNGCitrusTest.run:70->AbstractTestNGCitrusTest.run:108->AbstractTestNGCitrusTest.invokeTestMethod:124 » TestCaseFailed

**Comment by svettwer** [comment]
Hi!

I've checked the project an you're right. The Bakery sample is currently not working.
Nevertheless, please note that citrus has moved to an github organisation.
https://github.com/citrusframework

There you'll find the actual sample projects etc.
I've moved this issue for you to keep track!
https://github.com/citrusframework/citrus-samples/issues/30

BR,
Sven
